name: Release and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Release with axion-release-plugin
      run: ./gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly
    
    - name: Get the new version
      id: get_version
      run: echo "{version}={$(./gradlew currentVersion)}" >> $GITHUB_ENV
    
    - name: Get JAR file name
      id: getjar
      run: echo "{jarfile}={$(ls build/libs/*.jar | head -n 1)}" >> $GITHUB_ENV

    - name: Create GitHub release
      run: |
        gh release create v$versiob $jarfile -t "Release v$version" -n "Release v$version"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
